version: "3.7"

services:
  yspotify:
    build: .
    container_name: yspotify
    restart: unless-stopped
    ports:
      - "50000:80"
    volumes:
      - yspotify:/home/node/data:rw
    env_file:
      - .env

volumes:
  yspotify:
    name: yspotify
    driver: local
